BACKEND="gfw-knocker"
ROLE="client"
PAQET_VERSION="v1.0.1"
PAQCTL_VERSION="22.04.5 LTS (Jammy Jellyfish)"
LISTEN_PORT=""
SOCKS_PORT=""
INTERFACE=""
LOCAL_IP=""
GATEWAY_MAC=""
ENCRYPTION_KEY=""
PAQET_TCP_LOCAL_FLAG="PA"
PAQET_TCP_REMOTE_FLAG="PA"
REMOTE_SERVER=""
GFK_VIO_PORT="45000"
GFK_VIO_CLIENT_PORT="40000"
GFK_QUIC_PORT="25000"
GFK_QUIC_CLIENT_PORT="20000"
GFK_AUTH_CODE="kUeqIeJDLsb2l8mX"
GFK_PORT_MAPPINGS="14000:444"
GFK_SOCKS_PORT=""
GFK_SOCKS_VIO_PORT=""
XRAY_PANEL_DETECTED="false"
MICROSOCKS_PORT=""
GFK_SERVER_IP="IP-VPS"
GFK_TCP_FLAGS="AP"
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
TELEGRAM_INTERVAL=6
TELEGRAM_ENABLED=false
TELEGRAM_ALERTS_ENABLED=true
TELEGRAM_DAILY_SUMMARY=true
TELEGRAM_WEEKLY_SUMMARY=true
TELEGRAM_SERVER_LABEL=""
TELEGRAM_START_HOUR=0
