# GFW-knocker parameters - auto-generated by paqctl
# Do not edit manually

vps_ip = "91.107.245.11"
xray_server_ip_address = "127.0.0.1"

tcp_port_mapping = {14000: 444}
udp_port_mapping = {}

vio_tcp_server_port = 45000
vio_tcp_client_port = 40000
vio_udp_server_port = 35000
vio_udp_client_port = 30000

quic_server_port = 25000
quic_client_port = 20000
quic_local_ip = "127.0.0.1"

quic_idle_timeout = 86400
udp_timeout = 300
quic_mtu = 1420
quic_verify_cert = False
quic_max_data = 1073741824
quic_max_stream_data = 1073741824

quic_auth_code = "kUeqIeJDLsb2l8mX"

quic_cert_filepath = ("/opt/paqctl/gfk/cert.pem", "/opt/paqctl/gfk/key.pem")

tcp_flags = "AP"
